on:
  push:
    branches:
      - main

name: Standard Build

jobs:
  ci:
    name: CI - Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install && yarn test && yarn build
